services:
  redis:
    image: docker.dragonflydb.io/dragonflydb/dragonfly
    ports:
      - '6379:6379'

  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    environment:
      - REDIS_URL=redis://redis:6379/0
    ports:
      - '3000:3000'
    depends_on:
      - redis

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    ports:
      - '4321:4321'
    depends_on:
      - api

  collector:
    build:
      context: .
      dockerfile: apps/collector/Dockerfile
    environment:
      - REDIS_URL=redis://redis:6379/0
      - REDIS_EVENTS_STREAM=events
    env_file:
      - apps/collector/.env
    depends_on:
      - redis

  ankiworker:
    build:
      context: .
      dockerfile: apps/ankiworker/Dockerfile
    environment:
      - REDIS_URL=redis://redis:6379/0
      - REDIS_EVENTS_STREAM=events
    env_file:
      - apps/ankiworker/.env
    depends_on:
      - redis
